version: '3.7'

services:

  db:
    image: postgres:10.1-alpine
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
   
  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  celery:
    build: .
    command: celery -A sweet_mail.celery -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A sweet_mail.celery beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  
     
#volumes:
#  postgres_data: